sonyxperiadev/device-sony-yukon

overlay/frameworks/base/core/res/res/values/config.xml
=> overlay: use lollipop's new screen off animation

rootdir/init.yukon.rc, rootdir/ueventd.yukon.rc
=> nfc: add permissions for open source NFC HAL

device.mk, kernel-headers/sound/audio_effects.h, kernel-headers/sound/compress_offload.h, kernel-headers/sound/compress_params.h, rootdir/system/etc/audio_effects.conf
this contains i. e. hw equalizer and offload support
=> audio: copy audio effects from hammerhead

overlay/frameworks/base/core/res/res/values/config.xml, overlay/frameworks/base/packages/SettingsProvider/res/values/defaults.xml, overlay/frameworks/base/packages/SystemUI/res/values/defaults.xml
rearranged to match other AOSP configs, new Values taken from factory
images, nexus configs and our other AOSP configs
=> yukon: clean up overlays

BoardConfig.mk
=> Increase memory cmdline parameter

device.mk
=> yukon: set dalvik tag

rootdir/init.yukon.rc
If fine, will cherrypick to other platforms.
=> init.yukon.rc: Fix USB OTG disk

rootdir/init.yukon.rc
https://github.com/android/platform_system_core/commit/5c3c77ed7855d262645c44b7e239476d9b66393d
=> init.yukon.rc: Remove WiFi directory creation

overlay/packages/inputmethods/LatinIME/java/res/values/gesture-input.xml, rootdir/init.yukon.rc
=> yukon: LatinIME: enable input gesture

rootdir/init.yukon.rc
=> init.yukon.rc: Remove /data/misc/wifi/sockets

system.prop
remove uneeded wifi props not needed by this project
=> yukon: clean props

device.mk
Added missing sensors and hardware permissions: Stepcounter
Stepdetector
Bluetooth_le
=> yukon: update permissions

rootdir/init.yukon.pwr.rc
remove uneeded/not exist paths
=> yukon: init.pwr.rc cleanup

rootdir/init.yukon.rc, rootdir/ueventd.yukon.rc
=> yukon: bluetooth: Assign bluetooth resources to bt stack group

BoardConfig.mk, sepolicy/addrsetup.te, sepolicy/device.te, sepolicy/file.te, sepolicy/file_contexts, sepolicy/property.te, sepolicy/property_contexts, sepolicy/sct.te, sepolicy/sensors.te, sepolicy/service.te, sepolicy/service_contexts, sepolicy/system_app.te, sepolicy/ta_qmi.te, sepolicy/tad.te, sepolicy/thermanager.te, sepolicy/timekeep.te
all good except the timekeep problems below.
=> sepolicy: include initial sepolicy

README.md, device.mk, rootdir/init.yukon.rc, system.prop
=> yukon: Sources cleanup

device.mk
Remove old and deprecated packages
=> yukon: Package cleanup

rootdir/init.yukon.rc
This change is part of:
https://android.googlesource.com/device/lge/hammerhead/+/38dcd1fc134a844e0e2f78b0e4e7e52a90afad79
=> yukon: Remove deprecated permission

device.mk
Bug: 20658562
Change-Id: Ib8e47b3edd94b1977c294959cdde01a54b64f123
Signed-off-by: Thierry Strudel <tstrudel@google.com>
=> yukon: Force dex2oat not to use swap file

rootdir/system/etc/media_profiles.xml
following nexus configuration for M
=> yukon: remove video editor from media_profiles

device.mk
Enable MultiWindow as described here:
http://forum.xda-developers.com/showpost.php?p=63230682&postcount=85
=> yukon: enable MultiWindow

BoardConfig.mk
=> yukon: define nfc chip type for new implementation

overlay/frameworks/base/core/res/res/values/config.xml
Used by Google Play Services if available
=> yukon: let us use Google Provider for gps

overlay/frameworks/base/core/res/res/values/config.xml
more info: https://github.com/android/platform_frameworks_base/commit/8c621ef54630e411d50e9ba1d8d8ed19ef93f9e1
=> yukon: Add support for static RadioCapabilities

BoardConfig.mk
=> yukon: Remove deprecated BOARD_NFC_HAL_SUFFIX

device.mk, rootdir/system/etc/media_codecs.xml, rootdir/system/etc/media_codecs_performance.xml
=> yukon: use hammerhead's media_codecs

device.mk
=> yukon: Add new camera2 hardware features

sepolicy/file_contexts
=> yukon: selabel recovery partition

device.mk
=> yukon: Move NFC HAL build name to device

kernel-headers/linux/pn547.h, kernel-headers/sound/compress_params.h
reflect current LA.BF64.1.2.2_rb4.7 kernelheaders
Testbuild succeeded on Eagle
=> yukon: update kernel headers

platform.mk
=> yukon: cleanup platform.mk

rootdir/ueventd.yukon.rc
=> yukon: add permissions for hw effects

platform.mk
=> Yukon: Build InCallUI
