- rootdir/init.yukon.pwr.rc
CAF (crazily) sets this to 787MHz, but at least factory
images correctly set this to 300MHz.
> Don't burn the CPU: scaling_min_freq 300000

- rootdir/system/etc/gps.conf
GPS lock in ~10 seconds versus ~90+ seconds
> gps: enable XTRA servers for quick A-GPS lock

- rootdir/init.yukon.rc
- rootdir/system/etc/init.yukon.bt.sh
- rootdir/ueventd.yukon.rc
It was anyway wrong and on 3.10 kernel those changes are
required for BTS402x to get initialized correctly.
> Fix bluetooth initialization

- BoardConfig.mk
switch to out/...../dts folder to be able to use dtb files for both inline and
prebuilt kernels
Signed-off-by: Aleksi Suomalainen <suomalainen.aleksi@gmail.com>
> mkqcdtimage: use dts from out folder

- BoardConfig.mk
This is just wrong, and hardcoded paths are always bad.
If anything, this should use $(OUT_DIR), or the proper kernel paths as needed.
> Revert "mkqcdtimage: use dts from out folder"

- rootdir/init.yukon.pwr.rc
This is needed for 3.10 kernel, where standalone_power_collapse
is almost totally broken for MSM8226 (A7 CPUs), leading to
hardlocks at runtime suspend time.
Using retention we will still save enough power, also because, if
we use an automatic hotplug mechanism, the CPUs will be suspended
and consequently power collapsed.
When the CPUs are UP and idle, we're still saving some power because
retention is a low power state where only the actual core is clock
gated, but the registers associated with the core are being retained,
hence the voltage will be retained too, but it will be reduced to a
really small value to keep the current CPU registers active.
This will also make us to resume the core faster from the idle state,
as the kernel won't have to warm-boot again to be able to resume …
> power: Enable sched_wake_to_idle and retention on cpu1-3

- rootdir/init.yukon.rc
low memory killer is not calculating the minfree paremeters correctly,
resulting in processes being killed before boot has even completed.
Set the minfree values manually and prevent any changes.
> yukon: configure low memory killer manually

- rootdir/init.yukon.rc
I didn't try this out yet, but it should be okay
> init.yukon.rc: Use timekeep instead of time_daemon

- BoardConfig.mk
BOARD_USES_GENERIC_AUDIO is commented out. And setting it to false makes no sense?
https://android.googlesource.com/platform/hardware/libhardware_legacy/+/android-5.0.2_r1/audio/Android.mk
> Remove BOARD_USES_GENERIC_AUDIO

- Android.mk
Since dsds is supported in kernel side, it can be added to device tree too.
> yukon: Add tianchi_dsds support

- rootdir/init.yukon.rc
Reverts sonyxperiadev/device-sony-yukon#48
It *should* not be world readable, as it contains the IMEI and serial number.
> Revert "yukon: fix cmdline permission"

- rootdir/ueventd.yukon.rc
needed by libqdutils and libqdMetaData
> yukon: Fix video nodes permission

- device.mk
Eagle, Flamingo, Seagull and Tianchi are calling: aosp_base.mk
telephony.mk
in AOSP telephony.mk is calling (Dialer): https://android.googlesource.com/platform/build/+/android-5.1.0_r3/target/product/telephony.mk
in AOSP aosp_base.mk calls others .mk as core.mk who is calling (Email and Exchange2) (Strings 35 and 36): https://android.googlesource.com/platform/build/+/android-5.1.0_r3/target/product/core.mk
> yukon: remove overrides packages

- system.prop
Streaming an embeded video in browser seems to cause high CPU
Enabling smooth streaming to relieve this.
> yukon: enable smooth streaming

- system.prop
Seems to work fine. Feels okay, vsync_event is created.
This was tested on BF64 kernel, and CAF HALs, therefore, behaviour on AOSP could be different.
Feel free to reject if there's a reason for it.
> yukon: Don't use fake vsync

- rootdir/system/etc/audio_policy.conf
Only list 48000 Hz in supported sampling rates
for remote submix
output and input stream profiles to avoid mismatch betwen playback
and capture
> yukon: fix remote submix sampling rates

- device.mk
AOSP builds is ignoring our audio_effects.conf at the start of build.
Correct the paths instead of system/etc/audio_effects.conf ---> system/vendor/etc/audio_effects.conf as hammerhead
See (string 170): https://android.googlesource.com/device/lge/hammerhead/+/android-5.1.1_r1/device.mk
> yukon: copy audio_effects to correct way

- BoardConfig.mk
Currently, the FrameBuffer in AOSP is double-buffering.
That's bad in cases when Compositor takes time near 16ms or less.
There're so many blockers('WaitForever') in several composition periods which makes janks. While we make it triple-buffering, those blockers disappear
> yukon: set Num of surface buffers to 3

- rootdir/init.yukon.rc
deleted not exist format_3d: ls -l /sys/class/graphics/fb1/format_3d: No such file or directory
Add missing chown system graphics /sys/class/graphics/fb1/video_mode (init.yukon.rc)
> yukon: ramdisk: fix for video nodes

- rootdir/init.yukon.rc
E/qdhwcomposer(  255): void qhwc::adWrite(const int&): Failed to open /sys/class/graphics/fb2/ad with error Permission denied
> yukon: avoid fb2 denials

- device.mk
https://android.googlesource.com/platform/hardware/qcom/gps/+/android-5.1.1_r1/core/Android.mk
> yukon: add missing libloc_core for gps

- rootdir/init.yukon.rc
Launch QMUXD as root to enable it to obtain AP_BLOCK_SUSPEND
capability to acquire wakelock during suspend.
QMUXD will downgrade itself to user radio after getting the
necessary capabilities.
fix:
E/QC-QMI ( 396): linux_qmi_qmux_io_wake_lock: Err in writing wakelock=qmuxd_port_wl_0, error [1:Operation not permitted]
E/QC-QMI ( 396): linux_qmi_qmux_io_wake_unlock: Err in writing wakelock=qmuxd_port_wl_0, error [1:Operation not permitted]
E/QC-QMI ( 396): linux_qmi_qmux_io_wake_lock: Err in writing wakelock=qmuxd_port_wl_0, error [1:Operation not permitted]
E/QC-QMI ( 396): linux_qmi_qmux_io_wake_unlock: Err in writing wakelock=qmuxd_port_wl_0, error [1:Operation not permitted]
E/QC-QMI ( 396): linux_qmi_qmux_io_wake_lock: Err in writing wakelock=qmuxd_port_wl_0, error [1:Operation not …
> yukon: init: qmux: Launch QMUXD process as root user

- device.mk
> yukon: typo: libtinymix -> tinymix

- BoardConfig.mk
This is needed in case sooner or later the default will change.
> [Yukon] BoardConfig: Specify not to build any bootloader

- device.mk
The 'error' messages are telling us we don't have an external radio,
but of course we have an integrated radio, so networking works fine.
The fix would be to modify the proprietary QMI code, but it's easier
to simply hide it.
**Perhaps keep this open until seagull networking is fixed.**
> yukon: qmi: stop the missing modem logspam

- device.mk
optional, but used by several services when present, including chromium
> yukon: build libemoji.so

- rootdir/init.yukon.rc
also, add support for legacy paths
fix:
W/MediaScanner( 1123): Error opening directory '/storage/usbdisk/', skipping: Permission denied.
> yukon: init: fix media scanner permissions

- rootdir/system/etc/audio_effects.conf
actually in vendor/sony/qcom/prebuilt/proprietary/vendor/lib/soundfx we have 3 blobs provided by Sony (libqcbassboost.so, libqcreverb.so, libqcvirt.so) those are required by:
https://github.com/sonyxperiadev/device-sony-shinano/blob/master/device.mk#L104
https://github.com/sonyxperiadev/device-sony-shinano/blob/master/device.mk#L105
https://github.com/sonyxperiadev/device-sony-shinano/blob/master/device.mk#L107
so adding them to audio_effects.conf for make them work
> yukon: use proper qcom audio_effects

- device.mk
these are not defined by available RAM
> yukon: use default aosp props

- rootdir/init.yukon.rc
The operating system can detect when an application is reading
data sequentially from a file or from disk.
In such cases, it performs an intelligent read-ahead algorithm,
whereby more data than is requested by the user is read from disk.
Thus, when the user next attempts to read a block of data, it will
already by in the operating system's page cache.
The potential down side to this is that the operating system can
read more data from disk than necessary, which occupies space in
the page cache until it is evicted because of high memory pressure.
Having multiple processes doing false read-ahead would increase
memory pressure in this circumstance.
So, this change reduces read_ahead_kb value from 2048 to 512 then
this setting tells the operating system not to read extra bytes,
which can …
> yukon: init: decrease read ahead buffer size

- system.prop
on this commit: https://github.com/sonyxperiadev/kernel/commit/20a6eb95259e965b9cfa72cb156ac3f384d2c39a // we can see as our actual kernel is using 0X8010 for black instead 0X8080 who is gray
aosp is using 0X8080 on actual android-5.1.1_r4 branch: https://android.googlesource.com/platform/hardware/qcom/media/+/android-5.1.1_r4/mm-video-v4l2/vidc/vdec/src/omx_vdec_msm8974.cpp (see string 129)
so change actual 0X8080 black with that one used by our kernel who is 0X8010 via prop persist.vidc.dec.conceal_color // commit 960a885dd7112b852c183ba5cad699ee24ae3a05 for platform/hardware/qcom/media
> yukon: use proper black conceal color for our kernel 3.10

- kernel-headers/uapi/linux/msm_mdp.h
- kernel-headers/uapi/video/msm_hdmi_modes.h
As subject, there were some changes in the kernel and the
headers needs to be updated.
Updated headers:
* uapi/linux/msm_mdp.h
* uapi/video/msm_hdmi_modes.h
> YUKON Update headers to reflect latest changes on 3.10 kernel

- rootdir/init.yukon.rc
- sepolicy/file_contexts
> sepolicy: update for blobs moved to /vendor/bin

- rootdir/init.yukon.rc
- rootdir/ueventd.yukon.rc
new NFC HAL uses generic /dev/pn54x while old one uses /dev/pn547
this change enshures compatibility for both cases
Change-Id: I073d417f220d44e5f37603310fef4782cc28f786
Signed-off-by: Alin Jerpelea <alin.jerpelea@sonymobile.com>
> update PN54x compatibility symlinks

- device.mk
on start of the system I can see a log saying:
E/qdhwcomposer (283): FATAL ERROR: copybit hw module not found --> avoid it building from source
> yukon: build copybit

- device.mk
needed for audio on android 6.0.0
more info: https://source.android.com/devices/audio/midi.html
> yukon: Add MIDI support

- overlay/frameworks/base/packages/SettingsProvider/res/values/defaults.xml
actually we are using that defined on: https://android.googlesource.com/platform/frameworks/base/+/android-6.0.0_r1/packages/SettingsProvider/res/values/defaults.xml#56
but the correct for marshmallow is defined on device/sample: https://android.googlesource.com/device/sample/+/android-6.0.0_r1/overlays/backup/frameworks/base/packages/SettingsProvider/res/values/defaults.xml#20
> yukon: update backup service for apps

- system.prop
This reverts commit 13d994af115ce9c387c27545a611b84cd005da65.
see: https://android.googlesource.com/platform/hardware/qcom/media/+/android-6.0.0_r1/mm-video-v4l2/vidc/vdec/src/omx_vdec_msm8974.cpp#132
Conflicts:
system.prop
> Revert "yukon: use proper black conceal color for our kernel 3.10"

- device.mk
those already defined by aosp
librs_jni --> https://android.googlesource.com/platform/build/+/android-5.1.1_r24/target/product/generic_no_telephony.mk#38
com.android.future.usb.accessory --> https://android.googlesource.com/platform/build/+/android-5.1.1_r24/target/product/core_minimal.mk#35
e2fsck --> https://android.googlesource.com/platform/build/+/android-5.1.1_r24/target/product/core_minimal.mk#66
> yukon: remove double packages

- device.mk
all targets (eagle flamingo tianchi seagull) are tracking aosp_base.mk & telephony.mk
well those are not including this: https://android.googlesource.com/platform/build/+/f29b5bd380e5ecced9bfa1d241e8b47448c29040%5E%21/#F
which let's without proper mms app on AOSP... so include it on our commons
> yukon: compile new AOSP messaging app

- rootdir/init.yukon.rc
Remove full arch path and call only lib name then the system
will preload it correctly.
> yukon: Fix dynamic linker for boringssl-compat

- rootdir/init.yukon.usb.rc
under developer options there is an option where user can choice about USB connection state one of these is charging mode only
which let's to charge the phone without enable adb services
> yukon: Add charge only USB mode

- device.mk
The variable persist.sys.usb.config is no longer honored by the framework,
and it's presence causes unnecessary toggling of the USB driver, which
disconnects ADB and makes the device's connection unstable.
Delete it.
> yukon: Remove persist.sys.usb.config override

- overlay/frameworks/base/core/res/res/values/config.xml
this is considered all the time by aosp and without this we finish with gps not working
re-add it to make it work
https://drive.google.com/file/d/0B-e5eQvKq2t2UGs2dVlYblhlSUU/view?usp=sharing
> yukon: re-add aosp flp location provider

- rootdir/init.yukon.rc
This is the correct name of the service, as necessitated by qcom/sepolicy
https://github.com/sonyxperiadev/device-qcom-sepolicy/blob/master/common/wcnss_service.te
I had already fixed this when creating initial platform sepolicy
https://github.com/sonyxperiadev/device-sony-yukon/commit/8266751278d507d88fd4afc4857fc332adddd3ab
But the fix got blown away in a 'clean up' of comments and whitespaces.
https://github.com/sonyxperiadev/device-sony-yukon/commit/c56294c0211394f44102e87100a9ed14dd65b525
Without this name the service has no sepolicy and so cannot function when in enforcing mode.
> Fix (again) the 'wcnss_service' service name

- rootdir/system/etc/media_profiles.xml
The current implementation does not support this resolutions right now.
Signed-off-by: Julien Bolard <jbolard@genymobile.com>
> yukon: disable 1080p resolution on back camera to avoid crashes

- rootdir/init.yukon.rc
look: https://github.com/sonyxperiadev/device-qcom-sepolicy/blob/master/common/wcnss_service.te
Conflicts:
rootdir/init.yukon.rc
> yukon: fix service typo

- rootdir/init.yukon.pwr.rc
"ondemand" governor is deprecated, several of the sysfs paths no
longer exist. All qcom soc on 3.10 kernels now use "interactive"
governor. Adapt config from msm8916 (also quad core 1.2-1.4GHz).
> yukon: update init.yukon.pwr.rc for 3.10 kernels

- rootdir/init.yukon.rc
LMK on 1.2.2 kernel is now working fine. In fact these forced
settings are now causing performance problems, as RAM usage
will hit 100% but LMK will not kill any tasks.
This reverts commit e0776c687d23522664cf1a3915ca09ba4031b862.
> Revert "yukon: configure low memory killer manually"

- device.mk
those are defined at qcom-vendor.mk in vendor files
> yukon: remove vendor products

- sepolicy/init.te
Avoid
[   10.530386] type=1400 audit(2390896.719:6): avc: denied { write } for pid=1 comm="init" name="wcnss_wlan" dev="tmpfs" ino=7375 scontext=u:r:init:s0 tcontext=u:object_r:wcnss_device:s0 tclass=chr_file permissive=1
> yukon: add init.te

- sepolicy/file_contexts
- sepolicy/mediaserver.te
Avoid
22.277835] type=1400 audit(1453397071.649:11): avc: denied { write } for pid=310 comm=mediaserver name=delta dev=mmcblk0p25 ino=390981 scontext=u:r:mediaserver:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[   22.277928] type=1400 audit(1453397071.649:12): avc: denied { add_name } for pid=310 comm=mediaserver name=Bluetooth_cal.acdbdelta scontext=u:r:mediaserver:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[   22.278041] type=1400 audit(1453397071.649:13): avc: denied { create } for pid=310 comm=mediaserver name=Bluetooth_cal.acdbdelta scontext=u:r:mediaserver:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[   22.278129] type=1400 audit(1453397071.649:14): avc: denied { open } for pid=310 comm=mediaserver …
> yukon: SELinux for acdb files

- rootdir/init.yukon.rc
readahead values:
sonyxperiadev/kernel@02246ee
> yukon: init: Use predefined readahead values from kernel

- power/power.c
BUG on aosp:
Enable Saver mode ... after that you can't disable it anymore causing reboots also if you connect usb it causes reboots too
Thanks @kholk
> yukon: powerhal: fix saver mode on/off

- sepolicy/zygote.te
Avoid
[   17.563100] type=1400 audit(1454011194.679:23): avc: denied { listen } for pid=302 comm=main path=/dev/socket/zygote scontext=u:r:zygote:s0 tcontext=u:r:init:s0 tclass=unix_stream_socket permissive=1
[   70.511162] type=1400 audit(1454011247.629:25): avc: denied { accept } for pid=302 comm=main path=/dev/socket/zygote scontext=u:r:zygote:s0 tcontext=u:r:init:s0 tclass=unix_stream_socket permissive=1
[   70.511432] type=1400 audit(1454011247.629:26): avc: denied { setopt } for pid=302 comm=main path=/dev/socket/zygote scontext=u:r:zygote:s0 tcontext=u:r:init:s0 tclass=unix_stream_socket permissive=1
[   70.512302] type=1400 audit(1454011247.629:27): avc: denied { getopt } for pid=302 comm=main path=/dev/socket/zygote scontext=u:r:zygote:s0 tcontext=u:r:init:s0 …
> yukon: add zygote.te

- rootdir/system/etc/audio_effects.conf
not using
pre_processing {
voice_communication {
aec {
}
ns {
}
}
}
it is specific for hammerhead
> yukon: use hammerhead's audio_effects

- rootdir/init.recovery.yukon.rc
link to /dev/block/bootdevice else in recovery partitions are not mountable.
tested on TWRP recovery
> yukon: recovery: add missing symlink

- rootdir/ueventd.yukon.rc
Since lights HAL is unified then all platforms
should be set this permission for system.
Change-Id: I70eac29371f566dc6e96f1802ae8b0e484a89093
> yukon: ueventd: Add common lights sysfs path

- platform.mk
Build Stk
there is not windy device in yukon family so it can be defined in yukon-common
> Yukon: Build Stk

- platform.mk
As discussed, it is not needed, and doesnt work anyway, as spaces in
overrides do not work and results into the build.prop entry being:
rild.libargs=-d
/dev/smd0
> yukon: remove rild.libargs

- PlatformConfig.mk
- rootdir/init.yukon.pwr.rc
- rootdir/ueventd.yukon.rc
- system.prop
Core limiting via msm_performance works well, but cpuquiet absolutely
hates it. rqbalance is not aware of msm_performance so it spams dmesg
because it cannot online a core for 'unknown' reasons.
We can achieve the same result using cpuquiet which rqbalance is
aware of. We can also have two sources of core limiting, power
profile and thermal.
We also need to tune rqbalance and cpuquiet per platform so also
move their system props.
> Move sysfs and props for cpuquiet hotplugging

- rootdir/init.yukon.pwr.rc
This change (ported from kk_mr2 branch) avoids to keep the LCD backlight always on causing a massive battery drain.
> Do not keep the LCD backlight always on
